- CMakeLists.txt
- gui/editor.cpp
- gui/editor.h
- gui/editor_model.cpp
- gui/level_dialog.cpp
- gui/main.cpp
- gui/map.cpp
- gui/preferences_dialog.cpp
- gui/preferences_dialog.h
Change working directory of editor to the directory of the YAML file being loaded, so that the relative paths of the drawing files can be used. Otherwise, absolute paths or other brittle paths are used, making the project files not load nicely across different machines and source-tree paths.
As a consequence, the path to the thumbnails and the thumbnail `model_list.yaml` file had to be saved somewhere, rather than just "hoping" that the thumbnail directory `thumbnails` happened to be already symlinked into the execution directory of `traffic-editor`. So this PR also adds in a `QSettings` instantiation to hold the absolute path of the `thumbnails` directory. For now, it is assumed to be the a sibling directory of the build directory, but the `thumbnails` path can now be edited …
> Change path on file load

- gui/vertex.cpp
no more guessing if it's a charger based on substrings with the vertex name!
> add is_charger vertex parameter

- gui/level_dialog.cpp
Closes #13
Small fix. Only return from the OK callback when the file is not found, but allow the callback to complete if the file exists.
Tested by adding a `png` file to a new level using the dialog. The resulting yaml section looks like this:
```
L3:
drawing:
filename: map.png
elevation: 0
```
Without this PR when selecting a `png` file on the dialog, and then pressing OK, nothing happens.
> Fix png files check in Level-Add dialog

- building_map_tools/building_map/generator.py
- building_map_tools/building_map_generators/building_map_nav.py
Instead of mashing a prefix followed by `_GRAPHNAME.yaml`, instead the nav graph generator now will take a directory name, and it will generate nav graphs of the form `GRAPHNAME.yaml` into that directory. This is easier to predict for downstream consumers of the graphs.
> output nav graphs by name into directory given as param

- traffic_editor/gui/editor.cpp
- traffic_editor/gui/editor.h
- traffic_editor/gui/map.cpp
- traffic_editor/gui/map.h
Using the "rotate model" tool now shows the pixmap model rotating in real-time with mouse motion, as opposed to only showing the rotation circle and "yaw=0" pointer moving. Also, you can hold `Shift` down while rotating, and it will snap to 45-degree discretizations, so it's easier to orient things to look nice.
> show model pixmaps rotating, with optional discretization

- building_map_tools/building_map/doors/door.py
- building_map_tools/building_map/doors/double_sliding_door.py
- building_map_tools/building_map/doors/double_swing_door.py
The simulated sliding doors were having trouble closing because the `0.01` limit was making them crash into each other.
> Tweaking limits on doors so they can close

- traffic_editor/gui/editor.cpp
- traffic_editor/gui/editor.h
* combine "Move Vertex" and "Move Model" tools into a single "Move" tool
* move toolbar to top of window
* prepare to migrate to graphics toolbar icons instead of textual buttons
> unify move-vertex and move-model tools. Toolbar on top.

- traffic_editor/gui/editor.cpp
- traffic_editor/gui/fiducial.cpp
- traffic_editor/gui/fiducial.h
- traffic_editor/gui/lift.cpp
- traffic_editor/gui/lift.h
- traffic_editor/gui/lift_dialog.cpp
- traffic_editor/gui/map.cpp
- traffic_editor/gui/map.h
* fiducial tool to specify easily-identifiable elements on floor plans (support pillars, etc.) to align the drawings of each level of a building. Currently assumes that the drawings are all rotated the same orientation, which is usually the case (so far at least) in what we've seen.
* use the level alignments to render the lift cabins correctly in all layers. Lift cabins are annotated manually against a "reference" level (for example, the basement) and then automatically translated/scaled to render correctly in all layers
* use the level alignments to keep the center of the viewport in the same location when switching between levels. This makes it much easier to verify lift doors are in the correct locations on all levels, etc.
* cache the transformations between levels, since they take a …
> Fiducials to align layers

- traffic_editor/CMakeLists.txt
- traffic_editor/gui/add_param_dialog.cpp
- traffic_editor/gui/editor.cpp
- traffic_editor/gui/editor.h
- traffic_editor/gui/level_dialog.cpp
- traffic_editor/gui/level_dialog.h
- traffic_editor/gui/level_table.cpp
- traffic_editor/gui/level_table.h
- traffic_editor/gui/lift_table.cpp
- traffic_editor/gui/map.cpp
- traffic_editor/gui/map.h
- traffic_editor/gui/map_dialog.cpp
- traffic_editor/gui/map_dialog.h
- traffic_editor/gui/map_view.cpp
- traffic_editor/gui/table_list.cpp
* top-level "map dialog" box to specify which level is the "reference level" that defines the coordinate frame
* explicit scale measurements are now only necessary on the reference level
* fiducial annotations now automatically set translation and scale relative to the reference level
* fix regression in selection of edges (walls, doors, etc.)
> Calculate and show scale using fiducials

- building_map_tools/building_map/doors/door.py
- building_map_tools/building_map/floor.py
Currently there is a bit of a feature difference between ignition and gazebo, so this is some minor changes backported from the ignition development branch to make implementation of a traffic editor that works for both easier, specifically:
- Add effort limit to door joints. If I understand correctly this is currently ignored in gazebo but works in ignition.
- Use the obj as a floor collision mesh. We were using obj for mesh and a polyline for collision before but polyline is not implemented in ignition yet. This change makes the obj used for both visual and collisions.
It would be nice to also start from a template and modify it since ignition requires a fair bit of common tags in the sdf to configure the gui and it gets very verbose to do it in Python (i.e. check …
> Port ign changes

- traffic_editor/gui/editor.cpp
This doesn't implement all of #63 but it should at least help reduce the number of clicks required to chain a bunch of vertices together to make walls (and lanes and other edges). You click on the first vertex, then you just move the mouse (not drag) to the next vertex, then when you click, it automatically starts drawing the next edge, so you can just click on the subsequent vertex to make a chain of walls. Clicking anywhere other than a vertex "resets" the tool.
> implement part of #63 so you can just keep clicking to chain vertices together

- traffic_editor/gui/editor.cpp
Otherwise requires a separate click with the "add vertex" tool. Now you can save a click (and a tool change). Implements #68
> create a new vertex if the add-edge click is not near an existing one

- building_map_tools/building_map/floor.py
- building_map_tools/building_map/level.py
Generate a single mesh (`.obj` file) for each level's walls, rather than instantiating a Gazebo primitive box for each wall segment. This makes a huge difference in very large worlds with thousands of wall segments.
> Generate wall meshes

- building_map_tools/building_map/floor.py
Eliminate duplicate floor vertices; apparently sometimes you can get duplicates which cause infinite recursion in the (re)triangulation process.
> simplify floor polygons to eliminate duplicate vertices

- building_map_tools/building_map/floor.py
- building_map_tools/building_map/hole.py
- building_map_tools/building_map/level.py
- building_map_tools/building_map/model.py
- traffic_editor/gui/building_level.cpp
- traffic_editor/gui/building_level.h
- traffic_editor/gui/editor.cpp
- traffic_editor/gui/editor.h
- traffic_editor/gui/polygon.h
- traffic_editor/gui/project.cpp
- traffic_editor/gui/project.h
- traffic_editor/resources/icons/door.svg
- traffic_editor/resources/icons/floor.svg
- traffic_editor/resources/icons/hole.svg
- traffic_editor/resources/icons/measurement.svg
- traffic_editor/resources/icons/wall.svg
- traffic_editor/resources/resource.qrc
* add a GUI tool to draw "hole" polygons on top of floors to annotate multi-level atriums
* incorporate holes into floor triangulations in `building_map_tools` when generating Gazebo worlds
* add a few more toolbar icons
> Floor holes

- building_map_tools/building_map/building.py
- building_map_tools/building_map/generator.py
- building_map_tools/building_map/level.py
- building_map_tools/building_map_generators/building_map_gazebo.py
- traffic_editor/gui/building_level.cpp
- traffic_editor/gui/building_level.h
- traffic_editor/gui/building_level_dialog.cpp
- traffic_editor/gui/building_level_dialog.h
Optionally flatten buildings, arranging each level on a user-specified XY offset. This mode is accessed by specifying a `flattened` argument to the building map generator. By default it is not used and a "physically realistic" Z stack is generated using the fiducial annotations for inter-level XY alignment.
> XY translation of each level in a 'flattened' world generation mode

- building_map_tools/building_map/doors/double_sliding_door.py
- building_map_tools/building_map/doors/double_swing_door.py
- building_map_tools/building_map/edge.py
- building_map_tools/building_map/level.py
* door-edge scaling was broken due to change in how we are "deferring" to compute scale (required to use fiducials). This PR calculates the door scale at the proper time in the sequence.
* restore collision bitmask to walls now that we're using polygonal mesh walls instead of box primitives as previously
> fix wall collision bitmask and door scaling issues

- building_map_tools/building_map/building.py
- building_map_tools/building_map/templates/gz_world.sdf
* generate plugin parameters for the toggle-floor GUI plugin, which is handy in very large buildings so that you can see what's going with the robots anywhere other than the top floor.
> generate params for toggle-floor GUI plugin

- building_map_tools/building_map/level.py
* this will prevent any issues when opening older `.building.yaml` files, that do not have the newer key names
> check if key in dict first

- building_map_tools/building_map/building.py
- building_map_tools/building_map/edge.py
- building_map_tools/building_map/fiducial.py
- building_map_tools/building_map/floor.py
- building_map_tools/building_map/level.py
- building_map_tools/building_map/model.py
- building_map_tools/building_map/transform.py
- building_map_tools/building_map/vertex.py
* use fiducial annotations on multi-floor buildings to align in rotation as well as scale and translation
* consolidate the 2D transform math in `building_map_tools` into its own Python class and apply the rotation/scale/translation only in a single place
> Calculate floorplan drawing rotations

- building_map_tools/building_map/transform.py
- building_map_tools/building_map_server/building_map_server.py
The map server was crashing since it was referring to a no-longer-existing member variable of level (scale).
Now it fills the message with the transform fields, also changed the defaults to floats and added them to the message for the future.
> Fix server to latest changes in level transform

- building_map_tools/package.xml
Add dependency to shapely so it can be installed through rosdep.
Sadly since rosdep is based on Python2 (hence installs the python2 version of the dependency) and we need the Python3 version it still doesn't quite work, but should be fine once the rosdep Python3 tool is used.
> Add dependency to python-shapely in package.xml

- building_map_tools/building_map/model.py
- traffic_editor/gui/building.cpp
- traffic_editor/gui/editor.cpp
- traffic_editor/gui/model.cpp
- traffic_editor/gui/model.h
* add GUI parameter for `static` attribute of simulation models
* use this attribute when generating SDF XML
* add a bit of spaghetti to try to preserve the existing (implicit) behavior
> Static parameter for models

- building_gazebo_plugins/CMakeLists.txt
* added target link to fix symbol errors when the plugin tries to link to the utils library
* changed to use `target_link_libraries` to allow linking to both local shared libraries as well as imported shared libraries
* fixes, https://github.com/osrf/rmf_demos/issues/38
> changed to using target_link_libraries to be specific

- building_map_tools/building_map/doors/double_swing_door.py
* simulation double swing doors direction was opposite of what was drawn on `traffic_editor`
> corrected simulation double swing door direction

- building_map_tools/building_map/building.py
- building_map_tools/building_map/templates/gz_world.sdf
- building_map_tools/building_map/templates/ign_world.sdf
Add the gui camera pose to ignition so it points to the same point as gazebo.
Also added the gui element to the gazebo template, so the camera pose will be in the beginning of the file (and there is a bit of saving in Python code).
> Add computed camera pose to ignition

- building_map_tools/building_map/doors/double_swing_door.py
- test_maps/CMakeLists.txt
- test_maps/maps/door_madness/door_madness.building.yaml
- test_maps/maps/door_madness/door_madness.project.yaml
- test_maps/package.xml
- traffic_editor/gui/editor.cpp
- traffic_editor/gui/project.cpp
* branch depending on sign of `motion_direction` for double hinged doors when generating simulation model
* use the `motion_degrees` parameter when generating double hinged doors
* add a test map package that has a pair of double swing doors (one with positive motion direction, one with negative motion direction) that will crash into vending machines if they open the incorrect direction
* fix an unrelated but annoying bug when trying to move models in the GUI when explicit scale or measurements were not provided
> branch on double swing door direction for sim generation

- building_gazebo_plugins/CMakeLists.txt
- building_gazebo_plugins/package.xml
- building_gazebo_plugins/src/slotcar.cpp
This PR addresses [issue 6](https://github.com/osrf/romi-dashboard/issues/4) for the romih dashboard.
To correctly initialize this `level_name` when the plugin is loaded, the plugin parses the `BuildingMap` msg as published by the `building_map_server` and identifies the level based on proximity of the spawned model to a waypoint on a level. Subsequently, the `level_name` is inferred from incoming `PathRequest` msgs which should take care of situations where the robot takes a lift to another level.
> Level name populated in Slotcar RobotState msg

- building_map_msgs/msg/Door.msg
- building_map_tools/building_map_server/building_map_server.py
- building_map_tools/building_map_server/test/test_map_client.py
PR #122 populated the BuildingMap msg with information on lifts and doors. However, it failed to transform positional data from pixel to SI units- this has been corrected here. Another change is the removal of redundant `door_name` field from Door msg (I had previously added this without noticing the existing `name` field above the comment block :man_facepalming: ).
> Fix coordinate frame of lifts and doors in building_map_server

- traffic_editor/thumbnail_generator/scripts/crop.py
I opened [this issue about thumbnail generator](https://github.com/osrf/traffic_editor/issues/146) yesterday. I went through crop.py and found that when a namespace is used cv2.imwrite would not be able to generate the cropped image because a directory for the namespace needs to be created first, so I made some small changes to crop.py and added a mkdir for the author name
> Fix not generating cropped image with namespace

- traffic_editor/thumbnail_generator/scripts/crop.py
Trivial fix following up on #147  just wrapping lines, so that the python style checker is happy.
> python line was too long

- traffic_editor/CMakeLists.txt
- traffic_editor/gui/editor.cpp
- traffic_editor/package.xml
With the change in `traffic_editor_assets` in https://github.com/osrf/traffic_editor_assets/pull/5 , there is no longer any need to pull the repository on build! This means that you no longer need an internet connection to have a successful build.
Instead, simply build `traffic_editor_assets` and `traffic_editor` will take care of the rest, dynamically resolving the location of `traffic_editor_asset`'s thumbnail directory instead of using a hidden folder in your home directory!
To test it, remember to remove the default preferences from `traffic_editor` in `~/.config/open-robotics` so that it will search for the default thumbnail path.
Then run `traffic-editor` and watch the console for its efforts in locating the `traffic_editor_assets` package (make sure the assets package is built and …
> Implement using thumbnails from installed traffic_editor_assets ament package

- building_map_tools/setup.cfg
When using `colcon build --symlink-install`, the installation method used for Python packages is different. It uses `python setup.py develop` instead of `python setup.py install` (see https://setuptools.readthedocs.io/en/latest/setuptools.html#development-mode). This requires a separate section in the `setup.cfg` file. Without it, the scripts get copied to the `<install-prefix>/bin` directory instead of `<install-prefix>/lib/<pkgname>`. They can be executed directly but will not work with `ros2 run`. In turn, this makes some of the tests fail because they can't find the building generator.
The fix is to add a `develop` section to `setup.cfg` that specifies where scripts should be linked to when installing in development mode. [See …
> Install scripts properly in symlink installs

- .github/workflows/build.yaml
- test_maps/CMakeLists.txt
* added reading CMAKE flag to prevent model downloading for build tests
* added flag during build test for `traffic_editor`, just in case needed for dependencies
> Allowed test_map to build without model downloading

- building_map_tools/building_map/model.py
- traffic_editor/gui/building.cpp
- traffic_editor/gui/editor.cpp
- traffic_editor/gui/editor.h
- traffic_editor/gui/model.cpp
- traffic_editor/gui/transform_dialog.ui
- traffic_editor/include/traffic_editor/building.h
Fix #156  by migrating towards the "typical" Cartesian angle convention of 0 radians = east, pi/2 radians = north. Because Qt uses the "geographic" convention of zero degrees = north, 90 degrees = east, we've flip-flopped on this a bit.
To deal with the past, there is now a GUI dialog in `Edit->Transform` that lets you enter an angle offset to "fix" maps that have the opposite convention. `Edit->Transform...` will instantly "fix" the `rmf_demos` office and airport maps if you enter `1.5708` :sparkles:
> consistent handling of model angles. Add GUI to transform all model yaw

- building_map_tools/pit_crew/pit_crew.py
#163 highlighted an issue when a user's Gazebo model directory does not exist.
This PR fixes that issue.
For output directories, it creates them.
For parsed directories, it logs a warning instead of throwing an assertion, and follows behaviour as if the parsed directory were empty instead of non-existent.
> Handle missing directories in pit_crew

- traffic_editor/gui/building_level.cpp
- traffic_editor/gui/fiducial.cpp
- traffic_editor/gui/level.cpp
- traffic_editor/gui/lift.cpp
- traffic_editor/gui/lift_door.cpp
- traffic_editor/gui/model.cpp
- traffic_editor/gui/project.cpp
- traffic_editor/gui/vertex.cpp
- traffic_editor/gui/yaml_utils.cpp
g++-9 and/or C++11/14 require the `cmath` header and `std::` namespace on various math functions used in the traffic editor GUI. g++8 probably wasn't being strict about these. Focal uses g++9 by default so they need to be fixed.
> Add missing includes and namespace usages for math functions

- building_map_tools/package.xml
Starting from Ubuntu Focal, depending on `python-shapely` won't work. There is a separate `rosdep` key for the Python 3 version of the package, `python3-shapely`. This package also exists on Ubuntu Bionic, so the dependency is changed to `python3-shapely`.
> Correct dependee to python3-shapely

- traffic_editor/gui/building.cpp
- traffic_editor/include/traffic_editor/building.h
Uhhh so... yeah. The double-ampersand doesn't mean what I thought it did :man_facepalming:
Nobody was using this function anyway; I was attempting to use it in a plugin and then realized that I don't know C++.
> so embarrassing. pretend this never happened.

- traffic_editor/gui/editor.cpp
- traffic_editor/gui/editor.h
Signed-off-by: Chen Bainian <brian97cbn@gmail.com>
This will allow add_edge function to snap either vertically or horizontally when **Shift** key is pressed.
I think this is especially good for alignment as #141 pointed out, This feature can also coexist with 141.
I follow the style of rotation. I will address the mouse_move part in a later PR since there are more changes.
> Add add_edge Shift key alignment feature

- traffic_editor/gui/building_level.cpp
- traffic_editor/gui/editor.cpp
- traffic_editor/gui/editor.h
- traffic_editor/gui/project.cpp
- traffic_editor/include/traffic_editor/rendering_options.h
When drawing large maps, sometimes it's helpful to hide all models so that it's easier to read the vertex names of their spawn points.
> view menu option to show/hide models

- building_map_tools/building_map_model_downloader/building_map_model_downloader.py
With the separation of concerns for the map generator and downloader, the downloader tool's help string was not updated. This PR fixes that.
> MINOR: Update map_model_downloader help

- building_map_tools/building_map_model_downloader/__init__.py
- building_map_tools/building_map_model_downloader/building_map_model_downloader.py
- building_map_tools/model_downloader/model_downloader.py
- building_map_tools/setup.py
Implements a convenience script for simpler model downloads
Simply rebuild `traffic_editor` and invoke:
```shell
$ ros2 run building_map_tools model_downloader -h
```
You can download models for all maps in a specified package by specifying the appropriate map package name.
Also supports listing available maps in the package using the `-l` or `--list` arguments
As well as downloading models for a subset of maps, using the `-s` or `--select-maps` arguments
(Standard `pit_crew` config args are also included. Allowing you to specify the model download directory as well as the pit_crew Fuel model cache.)
> Implement convenience script

- traffic_editor/gui/building_level.cpp
- traffic_editor/gui/editor.cpp
Simple fixes
- Was not able to delete polygon after creation, added this delete polygon function
- Floor polygon's param was not displaying on the properties box during initialization. added this
> simple fix on gui polygon removal and param display

- building_map_tools/building_map/building.py
Simple fix to handle buildings without `lifts` key defined.
Fixes #187
> handle situation when lifts key is not present

- traffic_editor/gui/building.cpp
So far in the traffic editor, when the user opens another map without closing the current one, the lifts from the previous map would remain on the map (and may be saved to the later opened map as well). So I added a line to clear the lifts before loading the new file. Now this issue should not appear anymore (at least I don't see it on my end after the addition).
> fix lifts not cleared when opening another project

- building_sim_plugins/building_gazebo_plugins/CMakeLists.txt
- building_sim_plugins/building_plugins_common/CMakeLists.txt
- building_sim_plugins/building_plugins_common/package.xml
This PR is aimed to fix the build errors as specified in https://github.com/osrf/traffic_editor/issues/198. 
There is an additional issue that seems to present, the name for the package `building_sim_common` does not correspond to the folder it is in: `building_plugin_common`: https://github.com/osrf/traffic_editor/blob/master/building_sim_plugins/building_plugins_common/CMakeLists.txt
This naming convention should be unified, but i'm wondering which name to follow: `plugin` or `sim`.
> Fix #198 and naming conventions

- traffic_editor/gui/editor.cpp
Trivial code change. As you moved the mouse around to place a model, it was rendering +90 degrees from what it would appear after you clicked the mouse. Now it doesn't. Thanks @MakinoharaShouko for pointing this out!
> fix initial model angle, so it doesn't rotate 90 degrees when placed

- traffic_editor/gui/building_level_dialog.cpp
- traffic_editor/gui/building_level_dialog.h
- traffic_editor/gui/building_level_table.cpp
In the current traffic editor, when the user renames a building level, the lift doors do not update and the lift doors on the old levels still remain in the .building.yaml file. This update should fix this problem. I have tested on my own computer and everything looks fine.
> Fixing lift doors not updated after renaming the levels

- traffic_editor/gui/building_level_dialog.cpp
When the building level changes, the model elevation did not change, this update fixes that.
Additionally, in [my last pull request](https://github.com/osrf/traffic_editor/pull/203), though the lift doors are updated as the level name changes, it would also remove the doors when the level name is not modified. The update also fixes that bug.
> Fixing model elevations not change & lift doors erased by mistake

- building_map_tools/building_map/level.py
- building_map_tools/building_map/model.py
The intent of the `z` parameter in a model in `traffic-editor` was to specify "height above the floor", for example, an item on a simulated countertop would be `z=1.0`. Then, the `building_map_generator` would stack things appropriately. Unfortunately, `building_map_generator` was ignoring the height of the level, and just copying `model.z` into the simulation world's instance of the model. This PR should fix that, so that the elevation of the building level of each model is used as intended.
> generate models at the correct Z height of their level

- README.md
I believe that since the GUI now has some ROS 2 dependencies, it needs to be built using `colcon`. This PR removes the text that previously said it could be built independently using "normal" standalone CMake.
> update top level readme installation instructions

- building_map_tools/building_map/lift.py
Addressing [this](https://answers.gazebosim.org/question/25677/prismatic-joint-for-lift-door-having-strange-behaviors-when-its-parent-lift-model-is-loaded-with-heavy-robots/) issue related to the lift's cabin door.
This seems to be an issue related to the missing moment of inertia of the lift cabin. When the simulated robot moves into the lift, the stopping position in the lift cabin is slightly off-centred. This resulted in slightly tilting the lift cabin, affecting the motion of the cabin door. (just my rough assumption)
Added inertia and tested it on my machine. Now the cabin door works fine. :tada:
> added inertia for lift cabin platform

- building_sim_plugins/building_plugins_common/include/building_sim_common/lift_common.hpp
- building_sim_plugins/building_plugins_common/src/lift_common.cpp
This PR updates lift `session_id` in the `lift_state` message each lift plugin stores and publishes. This is required for the new features in `rmf_core` to make robots check the `session_id` before entering the lift.
Additionally, a minor bug in `available_floors` displayed in `lift_state` messages is fixed.
> Update lift session id in lift plugin

- building_map_tools/building_map/building.py
- building_map_tools/building_map/level.py
- building_map_tools/building_map/lift.py
- building_sim_plugins/building_gazebo_plugins/src/lift.cpp
- building_sim_plugins/building_plugins_common/include/building_sim_common/lift_common.hpp
- building_sim_plugins/building_plugins_common/src/lift_common.cpp
- traffic_editor/gui/lift.cpp
- traffic_editor/gui/lift_dialog.cpp
- traffic_editor/gui/lift_dialog.h
- traffic_editor/include/traffic_editor/lift.h
This PR includes the following features:
- Adding a field in the lift dialog of traffic_editor GUI to specify the initial floor of the lift
- When the initial floor is not being served by the lift, the lift will be generated on the first floor instead
- If a lift is not serving any floor (i.e. having no doors open on any floor), the lift model will not be generated.
I am making this a draft PR, for now, to avoid conflicts with https://github.com/osrf/traffic_editor/pull/220. Once that is merged, I might change the lift shaft holes generation when lift model is not generated accordingly.
> Improve lift initial floor definition

- building_sim_plugins/building_ignition_plugins/src/slotcar.cpp
Create component in plugin's `Configure` method, to be used later for other purposes including dispensing onto/ingesting from slotcar.
> Create AxisAlignedBox component for slotcar

- building_map_tools/building_map/building.py
- building_map_tools/building_map/level.py
- building_map_tools/building_map/model.py
- building_sim_plugins/building_gazebo_plugins/CMakeLists.txt
- building_sim_plugins/building_gazebo_plugins/src/toggle_floors.cpp
This PR adds the feature of hiding & showing the static models on each level in the toggle_floors plugin. Static model names are recorded in the plugin sdf specification and hide/show messages are published on click of the toggle floor button.
> Implement model visibility toggling

- traffic_editor/gui/building.cpp
- traffic_editor/gui/editor.cpp
- traffic_editor/gui/project.cpp
- traffic_editor/gui/project.h
fixes #232 by adding a getter/setter for the `Project` class `filename` member, ensuring that whenever it's set, it validates that the building has a sane filename, and if not, it creates a default filename for it.
> fix #232 ensuring that building filename is set

- building_map_tools/building_map/wall.py
The previous implementation for multiple wall textures will fail during launch with `gazebo11`. Simple fix
> Fix multiple wall textures

- building_map_msgs/QUALITY_DECLARATION.md
- building_map_msgs/README.md
- building_map_tools/QUALITY_DECLARATION.md
- building_map_tools/README.md
- building_sim_plugins/building_gazebo_plugins/QUALITY_DECLARATION.md
- building_sim_plugins/building_gazebo_plugins/README.md
- building_sim_plugins/building_ignition_plugins/QUALITY_DECLARATION.md
- building_sim_plugins/building_ignition_plugins/README.md
- building_sim_plugins/building_plugins_common/QUALITY_DECLARATION.md
- building_sim_plugins/building_plugins_common/README.md
- test_maps/QUALITY_DECLARATION.md
- test_maps/README.md
- traffic_editor/QUALITY_DECLARATION.md
- traffic_editor/README.md
This PR adds [quality declaration documents](https://www.ros.org/reps/rep-2004.html) and (where necessary) basic README files too all packages in `traffic_editor`.
The message packages meet the requirements to be Quality Level 3. All source-code-containing packages are currently QL4.
We need to go over each declaration and discuss it, making sure we all agree on the arguments being made.
Once this PR goes in, we can make a list of tasks that need to be done to move the packages up to higher quality levels.
> Add first pass of quality declarations for all packages

- .github/workflows/build.yaml
- traffic_editor/CMakeLists.txt
- traffic_editor/gui/editor.cpp
- traffic_editor/gui/editor.h
- traffic_editor/gui/project.cpp
- traffic_editor/gui/project.h
- traffic_editor/gui/scenario.cpp
- traffic_editor/gui/scenario.h
This PR adds a bit of CMake logic and some `#ifdef` throughout the code so that it doesn't compile support for "traffic-editor simulation" plugins if `libignition-plugin` is not present. This will remove the previous hard dependency on `ignition-plugin` and make it a soft dependency, and since nobody is currently using that plugin interface, that seems like a good tradeoff. Hopefully now it will become possible to release this package as a binary, using the normal ROS package release flow.
> only build plugin support if ignition-plugin is present

- traffic_editor/gui/lift_dialog.cpp
* Bug occurs when default values in combo boxes are used, therefore nothing gets saved into the lift's internal states. The only saving mechanism was left to the `onTextChanged` signal
* Solves https://github.com/osrf/traffic_editor/issues/247
> Uncommented code block which saves lift parameters when OK is clicked, added initial_floor_name

- building_map_tools/building_map/building.py
- building_sim_plugins/building_plugins_common/include/building_sim_common/slotcar_common.hpp
Using colons for in tags creates issues when parsing XML files in Python, since the colon implements namespaces in the specification, for example while parsing a world I got the following error:
```
xml.etree.ElementTree.ParseError: unbound prefix: line 5819, column 4
```
Changing them to underscore fixes the issue.
> Fix namespace for rmf charging plugin

- building_sim_plugins/building_plugins_common/include/building_sim_common/slotcar_common.hpp
- building_sim_plugins/building_plugins_common/src/slotcar_common.cpp
This PR ensures that the RobotMode in the RobotState message published by the slotcar remains as `MODE_DOCKING` until another ModeRequest is received.
> Fixed RobotMode

- building_sim_plugins/building_plugins_common/include/building_sim_common/slotcar_common.hpp
- building_sim_plugins/building_plugins_common/src/slotcar_common.cpp
Modifies `compute_change_in_rotation` to choose a heading based on proximity to the commanded heading
in the slotcar's trajectory, instead of choosing a heading based off of the amount of rotation required.
> Determine slotcar target heading by proximity to the commanded heading in its trajectory

- building_sim_plugins/building_ignition_plugins/src/lift.cpp
Modifies lift plugin to issue either joint or model velocity commands based on the physics engine used.
> Enable lifts to work with TPE

- building_map_tools/building_map/doors/door.py
- traffic_editor/gui/lift.cpp
Signed-off-by: Chen Bainian <chenbn@artc.a-star.edu.sg>
I really love the new plugin disable feature. Here are some changes I made that should make the old yaml files backwards compatible.
This should resolve
- `test_map` **door** not building due to missing 'plugin' argument
- old map yaml unable to open in traffic editor due to missing 'plugins' bool field for **lift**
Also this should fix https://github.com/osrf/rmf_demos/issues/157
> Fix door, lift plugin disable options backwards compatibility

- building_sim_plugins/building_ignition_plugins/CMakeLists.txt
Fixes library lookup errors in ignition demos reported in [rmf_demos](https://github.com/osrf/rmf_demos/pull/152#issuecomment-721791154)
> Migrate ignition plugins to ament_target_dependencies

- traffic_editor/gui/building.cpp
During new project creation, the `crowd_sim_impl` pointer will be `nullptr` so the automatic save during creation explodes. This one-liner makes it not explode.
> check crowd sim impl pointer before deref

- traffic_editor/gui/editor.h
Traffic_editor wont compile when opencv is not installed but the ignition plugin is there. This will correct the compilation error.
> fix to compilation when no opencv

- building_sim_plugins/building_ignition_plugins/src/lift.cpp
- building_sim_plugins/building_ignition_plugins/src/slotcar.cpp
Reads or stores the `AxisAlignedBox` component in the Lift and Slotcar plugins before removing the component. Improves rtf when running Ignition demos since bounding box computation is expensive. 
We need to read this value beforehand instead of only creating the component when we need it because it usually takes at least one more update/preupdate iteration to compute the `AxisAlignedBox`.
> Remove Slotcar and Lift AAB components when not required to improve Ign Demos rtf

- building_sim_plugins/building_plugins_common/include/building_sim_common/slotcar_common.hpp
- building_sim_plugins/building_plugins_common/src/slotcar_common.cpp
`old_lin_vel` and `old_ang_vel` were not set upon initialization, causing the first iteration of the discharge calculation to output undefined values.
> Fix undefined initialization of _old_ang_vel and _old_lin_vel

- building_sim_plugins/building_plugins_common/CMakeLists.txt
Removing the cmake lines that are there to support eloquent. Master is not required to support eloquent and this should be left to the relevant branch. This lines also create problems at the buildfarm level.
Signed-off-by: Marco A. Gutierrez <marco@openrobotics.org>
> dropping eloquent support

- traffic_editor/gui/actions/add_edge.cpp
- traffic_editor/gui/editor.cpp
Addresses #275  at least for now, needs to be combined with the Undo work though after that PR is in.
> scale add-lane vertex snap distance correctly

- traffic_editor/gui/editor.cpp
- traffic_editor/gui/project.cpp
There was an `ifdef` block inserted during one of the code cleanups that was incorrect, and will cause rendering crashes during the second redraw of model thumbnails on systems where `libignition-plugin` is not detected. This is due to the way that the code is keeping raw pointers to Qt-owned graphics objects that become invalid when the scene is cleared. Removing this `ifdef` check ensures that the pointers to the model thumbnail `QPixmapItem` objects are always discarded when the scene is cleared.
> Fix thumbnail rendering crash

- traffic_editor/gui/building_level.cpp
- traffic_editor/gui/editor.cpp
- traffic_editor/gui/scenario_level.cpp
- traffic_editor/gui/vertex.cpp
- traffic_editor/include/traffic_editor/vertex.h
- traffic_editor/resources/icons/battery.svg
- traffic_editor/resources/icons/parking.svg
- traffic_editor/resources/icons/stopwatch.svg
- traffic_editor/resources/resource.qrc
This PR changes the shape of vertex icons to indicate if they are set to be holding and/or parking points in the navigation graph.
* holding points will be rendered as slightly larger squares
* parking points will have an outline of an even-larger square
* otherwise the vertex will be rendered as a circle, as before.
> change vertex shape for parking/holding points

- traffic_editor/gui/building_level.cpp
When we started to render using proper Z stacks, unfortunately the orientation icons were not assigned a Z height, so they were below everything. Fixed now.
> place orientation icon at correct Z stack so it's visible again

- traffic_editor/CMakeLists.txt
- traffic_editor/gui/actions/add_correspondence_point.cpp
- traffic_editor/gui/actions/add_correspondence_point.hpp
- traffic_editor/gui/actions/move_correspondence_point.cpp
- traffic_editor/gui/actions/move_correspondence_point.hpp
- traffic_editor/gui/building.cpp
- traffic_editor/gui/building_level.cpp
- traffic_editor/gui/correspondence_point.cpp
- traffic_editor/gui/editor.cpp
- traffic_editor/gui/editor.h
- traffic_editor/gui/layer.cpp
- traffic_editor/gui/project.cpp
- traffic_editor/gui/project.h
- traffic_editor/gui/scenario_level.h
- traffic_editor/include/traffic_editor/building.h
- traffic_editor/include/traffic_editor/building_level.h
- traffic_editor/include/traffic_editor/correspondence_point.hpp
- traffic_editor/include/traffic_editor/layer.h
- traffic_editor/include/traffic_editor/level.h
- traffic_editor/resources/icons/correspondence_point.svg
- traffic_editor/resources/resource.qrc
This adds the required UI to be able to specify correspondence points for each layer of a level, then save those correspondence points to a separate YAML file that can be used with the map transformer library.
> Add UI for adding correspondence points

- traffic_editor/gui/building_level.cpp
- traffic_editor/gui/editor.cpp
Check bounds of correspondence point vector. For newly-created levels, this can be empty and lead to :boom:   Fixes #295 
> hotfix for #295

- traffic_editor/gui/editor.cpp
- traffic_editor/gui/project.cpp
The add-edge tools were correctly exiting via right-click, but not via `[ESCAPE]` key. This PR just switches the order the underlying functions were being called to fix it. It also fixes an unrelated crash that resulted from exiting the tool correctly.
> correctly exit add-edge mode, fix #297

- building_map_tools/building_crowdsim/building_yaml_parse.py
- building_map_tools/building_crowdsim/config/configfile_generator.py
- building_map_tools/building_crowdsim/navmesh/navmesh_generator.py
Previously the `building_crowdsim` generator would throw Python exceptions (crash) if it didn't find the YAML keys it expected in the building files. This was not convenient if using a `cmake GLOB` to collect all the building files and generate their maps, since it would lead to broken builds if any of the buildings didn't have any human data. This PR tweaks `building_crowdsim` a bit so that it doesn't crash in this case and just exits cleanly without doing anything.
> allow parsing failures to not crash building_crowdsim

- .github/workflows/ci.yaml
- README.md
- traffic_editor/CMakeLists.txt
- traffic_editor/gui/crowd_sim/transition_table.cpp
- traffic_editor/gui/multi_select_combo_box.cpp
- traffic_editor/test/CMakeLists.txt
- traffic_editor/test/test_gui.cpp
This PR reworks the `cmake` of the `traffic_editor` package to make it testable, and creates a minimal QTest:
* move the GitHub workflows to `foxy` (they were on `eloquent` before)
* create a static library for all of the sources other than `main.cpp`
* builds the existing GUI by linking `main.cpp` with that static library (no change for users)
* creates a minimal QTest, `test_gui.cpp` also with that static library, and register it in `ament_cmake` so that it runs with `colcon test` and dumps its output in (I think) a workable format and place. At least it seems to work as expected when I create a failing `QCOMPARE()` in QTest, reporting the failure as expected with all the nice QTest log info.
* the minimal QTest just instantiates the `Editor` class and then deletes it, using the …
> Add minimal CI test

- traffic_editor/gui/building.cpp
- traffic_editor/gui/editor.cpp
Relative paths were not being handled properly when loading and saving. Also, the `ofstream` object was not being checked for validity, so this was a silent error and edits would not be written to disk, resulting in much confusion. Now an error box will pop up if the `ofstream` is not pointing to an actual file, and the relative vs. absolute filename handling is fixed.
> fixes #303, bug in loading/saving relative paths

- test_maps/CMakeLists.txt
The current way of getting the name of he map would fail if there's more than one map and there's a dot in the path to the maps. This will cause future releases with more than one map to fail in the buildfarm. The method to get the map name has been changed to use regex instead.
> Build fails when dot in path fix

- building_map_tools/building_map/building.py
- building_map_tools/building_map/edge.py
- building_map_tools/building_map/fiducial.py
- building_map_tools/building_map/floor.py
- building_map_tools/building_map/hole.py
- building_map_tools/building_map/level.py
- building_map_tools/building_map/lift.py
- building_map_tools/building_map/model.py
- building_map_tools/building_map/param_value.py
- building_map_tools/building_map/transform.py
- building_map_tools/building_map/vertex.py
- building_map_tools/building_map_combiner/building_map_combiner.py
This PR introduces a new Python program, `building_map_combiner` and implements its functionality in the `building_map` Python package. It allows you to add vertices and traffic lanes from one map into another map. As the vertices are being added, they will be transformed into the same coordinate space using fiducials, provided there exist at least 3 equally-named fiducials in each map. This was implemented primarily by refactoring the existing fiducial-alignment code used for multi-floor world generation into a form that could be used for multi-map alignment.
In order to implement this feature, it was also necessary to add map-writing `to_yaml()` functions throughout the `building_map` Python package. It would be nicer if the YAML flow/block style toggling was happening the same way in …
> building_map_tools feature: building_map_combiner

- building_sim_plugins/building_gazebo_plugins/src/crowd_simulator.cpp
- building_sim_plugins/building_ignition_plugins/src/crowd_simulator.cpp
- building_sim_plugins/building_plugins_common/include/building_sim_common/crowd_simulator_common.hpp
- building_sim_plugins/building_plugins_common/src/crowd_simulator_common.cpp
Previously, if `MENGE_RESOURCE_PATH` is not provided, the `crowd_sim` plugin will fail, resulted in failing to launch a demo world. Instead of failing, the minor change here is to disable `crowd_sim` if `MENGE_RESOURCE_PATH` is not provided. 
With this, a subsequent pr will consist of an optional `use_crowdsim` arg (e.g.  `XX.launch.xml use_crowdsim:=1` ) in the demo world launch files.
> Disable crowd sim without failing

- traffic_editor/gui/building.cpp
Since the `.project.yaml` file is no longer being used, this PR just adds a (hopefully) helpful console warning if a `.project.yaml` filename is passed on the command line.
> print console warning when trying to load project.yaml file

- rmf_traffic_editor/gui/crowd_sim/crowd_sim_impl.cpp
In certain conditions (especially when creating new buildings), a crash can be triggered by this line in the crowdsim `to_yaml()` function. Adding this one-line check avoids that situation.
> avoid crash in empty crowdsim save routine

- rmf_traffic_editor/gui/editor.cpp
- rmf_traffic_editor/gui/editor.h
- rmf_traffic_editor/gui/map_view.cpp
Fix #315 and provide a better solution for #311 by providing a zoom-reset menu action (for recovery) and a zoom-clamp calculation in the mouse-wheel handler to prevent the zoom factor from flying to zero, which make it impossible to recover.
> provide zoom-reset and clamp on scale factor

- rmf_building_map_tools/building_map_model_downloader/building_map_model_downloader.py
This PR addresses https://github.com/open-rmf/rmf_demos/pull/14#issuecomment-809037834.
According to input `buildiing.yaml` file, the `building_map_model_downloader` will automatically download the specified `crowd_sim` models/actors from fuel. Will ignore otherwise.
> auto download crowdsim models

- rmf_building_map_tools/building_map/floor.py
- rmf_building_map_tools/building_map/level.py
If a floor polygon had zero, one, or two vertices, building map generation would crash. This PR adds some checks for this case. Also removes some comment blocks and old debugging code.
> avoid crashing when generating undefined floor polygons. cleanup.

- rmf_traffic_editor/gui/layer_dialog.cpp
Immediately re-load layer image after filename is changed and OK is pressed in the layer edit dialog box. Fix #324.
> update layer image immediately after OK button

- rmf_traffic_editor/gui/editor.cpp
- rmf_traffic_editor/gui/editor.h
Previously, if two layers were added with the same name, it would be impossible to edit the second one, because the layer editing dialog was only searching layers by name, not by index. Now the layer dialog finds the requested layer by index in the layers table. Fix #325 
> handle editing multiple layers with same name.

- rmf_building_map_tools/building_map/utils.py
Similar to [rmf_demos #22](https://github.com/open-rmf/rmf_demos/pull/22), since `libsdformat11` ambient / diffuse values outside of the range dictated by the specification [0.0 - 1.0] cause runtime errors. This makes it impossible to run the scenarios in Ignition Edifice (and later version).
Scaled the door ambient and diffuse values down to the specification's range
> Fix material values for sdf compliance

- rmf_building_map_tools/building_map_server/building_map_server.py
Currently, `building_map_server` crashes on startup when a building-floorplan image file is missing. Because the floorplan images are only needed for UI's and not "the rest of RMF," this PR changes this crash to an error message in the log. Fixes #333
> building_map_server: don't crash when missing image file

- rmf_building_map_tools/building_map/floor.py
When generating floor models, every floor has its own texture and copies the same texture file over and over with different names. This caused a lot of unnecessary memory (and disk) usage, as well as longer simulation loading times.
This fix removes the textures duplication and makes each .mtl file point to a single shared texture.
I evaluated by running `nvidia-smi` with both ignition and gazebo classic on the `airport_terminal` world.
```
+-----------------------------------------------------------------------------+
| Processes:                                                                  |
|  GPU   GI   CI        PID   Type   Process name                  GPU Memory |
|        ID   ID                                                   Usage      | …
```
> [Optimization] Remove duplicated textures

- rmf_building_map_tools/building_map/wall.py
Walls' textures are now 2D instead of 1D, this allows mapping complex textures to wall and removing the glitches that appeared when some textures (such as tiles) were applied to walls.
To be fully honest I don't understand 100% the obj specification and whether the logic I added for the texture vertices is correct. I tried to follow the same ordering as the polygon vertices and "unwrap" the wall textures manually.
This implementation is only a starting point, followup work should parametrize texture scale for walls, as it happens for floors, as well as adding more wall specific textures. Now we are assuming 2.5m height x 1m width textures.
I split the results in a classic western way.
**The good**, what would happen if we parametrized the texture height and applied the correct scale to a …
> Convert wall textures from 1D to 2D

- rmf_building_map_tools/building_map/floor.py
- rmf_building_map_tools/building_map/level.py
- rmf_building_map_tools/building_map/material_utils.py
- rmf_building_map_tools/building_map/param_value.py
- rmf_building_map_tools/building_map/wall.py
This PR is a followup of #342, and is to work towards #343. It adds support to `rmf_building_map_tools` for PBR textures to be used in Ignition, specifically metalness, roughness, normal, environment and light maps.
The YAML format now has additional parameters for walls and floors that follow the same naming convention as the [SDF metal PBR workflow](http://sdformat.org/spec?ver=1.8&elem=material#pbr_metal).
For ease of review the PR doesn't yet include all the `rmf_traffic_editor` GUI work to include the parameters, hence they have to be added manually to the yaml file. An example gist for the office world that can be used to test the PR is [here](https://gist.github.com/luca-della-vedova/846103f59f0190dd3de59840052f49fe).
Followup work will be to add the parameters to the …
> PBR textures for walls and floors in Ignition Gazebo

- rmf_building_map_tools/building_map_model_downloader/building_map_model_downloader.py
- rmf_building_map_tools/pit_crew/pit_crew.py
1. Try to make model downloading more transparent during the package build process
2. Add functionality to filter models based on the availability of it in certain locations
3. Use Ignition fuel tools for downloading models for both classic gazebo and ignition gazebo instead of GET requests
1. Just added some additional logging statements. Transparency is difficult during build process as colcon build by default only prints outputs after a package has been build, unless explicit told [otherwise](https://colcon.readthedocs.io/en/released/reference/event-handler-arguments.html).
2. `-i` flag in `building_map_model_downloader.py` to specify which folder to look for models first.
3. `-f` flag in `building_map_model_downloader.py` to specify to use Ignition fuel tool to download models.
3.1 …
> improve building map tools

- rmf_traffic_editor/gui/building.cpp
- rmf_traffic_editor/gui/crowd_sim/crowd_sim_impl.cpp
This is a trivial PR that explicitly sets how whitespace (carriage returns and indents) are handled for a few places when serializing the `crowd_sim` data structure in YAML. The two forms are equivalent; this just causes `yaml-cpp` to generate whitespace in the same way that the JavaScript `yaml` library generates it when the emitter comes upon an empty sequence nested inside a block-style map. Otherwise, the two implementations (C++ and JavaScript) would generate whitespace diffs each time they saved each other's files.
Similarly, for empty lift maps (i.e. building models that do not have lifts), this PR forces a flow-style empty map `{}` to be generated in `yaml-cpp`, to force the whitespace to be generated identically by the `yaml-cpp` and JavaScript `yaml` libraries.
> Minor tweak to how empty crowd_sim and lift structures are serialized in YAML

- rmf_building_map_tools/building_map_model_downloader/building_map_model_downloader.py
- rmf_building_map_tools/pit_crew/pit_crew.py
1. #360. The folders downloaded by Ignition is always in lowercase, and so does the exported folders. This results in gazebo being unable to find the models.
2. #361 
1. Commit 6fa825f. Have the exported folders follow the original name of the models as described in the `building.yaml` file.
2. Commit abe741b. If exporting models, automatically check the export path for missing models.
> Fix issues with building map tools using Ignition tools

- rmf_traffic_editor/gui/building.cpp
If only one fiducial was defined on a level, previously it would try to divide by zero :facepalm:  when aligning the levels. This trivial PR just recognizes this case and returns the (0, 0, 0) transform. Fixes #366 discussed in https://github.com/open-rmf/rmf/discussions/69
> hotfix for #366, avoid exploding transform for 1 fudicual

- rmf_building_map_tools/building_map/material_utils.py
Closes #369, `building_map` crashing when there is no floor because of a `FileNotFound` error.  
When there is no floor, the floor generation function will be called and the script will go straight into wall generation. The issue was that the `meshes` folder might not have been created, it is done [here](https://github.com/open-rmf/rmf_traffic_editor/blob/main/rmf_building_map_tools/building_map/wall.py#L41-L43), however the `generate_wall_visual_mesh` function is called after the `add_pbr_material` which assumes that the folder exists.
The quick fix is to add a check in the [copy_texture](https://github.com/open-rmf/rmf_traffic_editor/blob/7043bffcdcc89e652b95985e8b1a519c08663d30/rmf_building_map_tools/building_map/material_utils.py#L20) function (called by `add_pbr_material`) for …
> Fix crash when level has no floors

- rmf_traffic_editor/gui/building.h
- rmf_traffic_editor/gui/editor.cpp
- rmf_traffic_editor/gui/editor.h
- rmf_traffic_editor/gui/level.cpp
- rmf_traffic_editor/gui/level.h
This PR adds multiple vertex selection by holding down SHIFT and clicking vertices to add them to the current selection. All selected vertices will all be rendered as red. You can clear the current selection by pressing the Escape key, as before.
When multiple vertices are selected that are directly connected by edges, you can press the slash key `/` or use the new menu item `Edit->Align Colinear`, and it will attempt to compute an orthogonal projection of all intermediate vertices onto the line between the first and last vertices in the selected chain.
There are probably corner cases that are not handled correctly, but at least it seems to work in the few situations that I've tried so far.
> Feature: align vertices colinear

- rmf_traffic_editor/gui/model_dialog.cpp
- rmf_traffic_editor/gui/model_dialog.h
This PR sorts the "add model" dialog box by the model name, instead of by the entire group_name/model_name string. This makes typing names quickly into the dialog edit box much faster. For example, as you start typing "desk", it will scroll the list to `OpenRobotics/Desk` and show the relevant preview. You don't have to type `OpenRobotics/Desk`
> sort list by model name, not Fuel group name

- rmf_traffic_editor/gui/building.cpp
- rmf_traffic_editor/gui/editor.cpp
- rmf_traffic_editor/gui/layer.cpp
- rmf_traffic_editor/gui/layer_table.cpp
- rmf_traffic_editor/gui/level.cpp
- rmf_traffic_editor/gui/level.h
- rmf_traffic_editor/gui/level_dialog.cpp
- rmf_traffic_editor/gui/level_table.cpp
- rmf_traffic_editor/gui/lift_dialog.cpp
- rmf_traffic_editor/gui/lift_table.cpp
- rmf_traffic_editor/gui/model.cpp
- rmf_traffic_editor/gui/model_dialog.cpp
- rmf_traffic_editor/gui/multi_select_combo_box.cpp
- rmf_traffic_editor/gui/rendering_options.cpp
- rmf_traffic_editor/gui/traffic_table.cpp
- rmf_traffic_editor/gui/yaml_utils.cpp
On some systems and some compilers, apparently the cascade of includes in some files in traffic-editor does not include `size_t` outside the `std` namespace, for some files. This PR just adds `std::` in front of all uses of `size_t` so that the code is more portable.
> resolve build error on some systems with size_t namespace

- rmf_building_map_tools/building_crowdsim/config/configfile_generator.py
Fixed bug #375: `building_crowdsim.py` unable to generate the required files for crowd simulation when no robot is added to the map due to a `ValueError` where the AgentGroup element fails its validity check
Added a condition in `configfile_generator.py` to only append AgentGroup to the scene file when there are robots in the map, denoted by length of the AgentGroup sub-elements.
Code can be tested by running `building_crowdsim.py` with a `.building.yaml` file with no robots added
> fix crowdsim map generation when there are no robots

- rmf_building_map_tools/pit_crew/pit_crew.py
Addresses https://github.com/open-rmf/rmf_traffic_editor/issues/386
Current implementation:
* downloads model to ~/.ignition folder, with whitespaces in names parsed as "%20"
* checks if there is whitespace in the model name
* If whitespace exists, rename "%20"-formatted name to whitespace name
the rename step fails when a model already exists with the whitespace name, which happens if the model was already downloaded in another demos package. This affects the export step involving the copy of the model from ~/.ignition folder to the workspace install folder.
PR is a quick fix targeting the rename step by ensuring any pre-existing model folder is removed, thus avoiding this failure. In the long term, it might be worth stripping whitespaces in fuel itself?
> fix whitespace issue in download chain

- rmf_building_map_tools/building_map/generator.py
- rmf_building_map_tools/package.xml
Use the `CLoader` and `CDumper` wrappers of `yaml-cpp` in `rmf_building_map_tools`. This gives significant speedup when loading/saving very large worlds with many thousands of vertices and lanes. Because `yaml-cpp` was already required for building `traffic-editor`, this is not a new dependency of RMF in general, we're just using it in more places now.
> Use yaml-cpp CLoader and CDumper from Python for speed

- rmf_traffic_editor/gui/building.cpp
- rmf_traffic_editor/gui/coordinate_system.cpp
- rmf_traffic_editor/gui/coordinate_system.h
- rmf_traffic_editor/gui/level.cpp
- rmf_traffic_editor/gui/level.h
- rmf_traffic_editor/gui/vertex.cpp
Because Cartesian maps have 1-meter units, we need to compute
a better default scale for them. Previously it was always using
a default scale of 0.05.
Somewhat related, also fix the edge-select implementation so it
spins through all edges in the map rather than just selecting
the first edge within 10 units... that was OK when we were always
using pixel-based maps, but now that meter-based maps are in use,
it was just choosing the first edge that was within 10 meters of
the click, which was a lot of edges and felt somewhat random.
> Improve behavior for Cartesian maps

- rmf_building_map_tools/building_map/building.py
- rmf_building_map_tools/building_map_converter/building_map_converter.py
- rmf_building_map_tools/building_map_server/building_map_server.py
Beginnings of GeoJSON support. This goes all the way back to #6 , almost exactly two years ago! This PR adds the following as a first step towards using GeoJSON more broadly in RMF:
* `building_map_server` will generate a compressed GeoJSON on-the-fly when starting up with a `.building.yaml` file, serving it on a separate `/site_map` topic, so that we can start to develop tools that use GeoJSON without breaking the existing `/map` topic.
* `building_map_converter` program uses the same functionality in the `building_map` Python package to convert `.building.yaml` files to either `.geojson` or `.geojson.gz`.
* This PR only converts the minimum amount of content from `.building.yaml` to `.geojson`: just vertices and lanes. Will add more as the POC develops.
We tried GeoPackage for a few …
> First steps towards GeoJSON

- .github/workflows/ci.yaml
- rmf_building_map_tools/building_crowdsim/building_yaml_parse.py
- rmf_building_map_tools/building_map/building.py
- rmf_building_map_tools/building_map/edge.py
- rmf_building_map_tools/building_map/edge_type.py
- rmf_building_map_tools/building_map/level.py
- rmf_building_map_tools/building_map_server/building_map_server.py
- rmf_building_map_tools/package.xml
- rmf_traffic_editor/gui/building.cpp
- rmf_traffic_editor/gui/level.cpp
- rmf_traffic_editor/gui/level.h
- rmf_traffic_editor/gui/level_dialog.cpp
Moving towards parsing and serving GeoJSON maps in `building_map_server` by creating the existing `BuildingMap` messages and serving them on `/map` as well as serving the GeoJSON on `/site_map`
This is slightly tricky because to avoid cross-referencing field ID's everywhere in the GeoJSON, instead we build an RTree of the `Point` features, and then use this to quickly identify the vertices that are the endpoints of each of the lanes, which are defined as `LineString` features.
Also fix a bug where Cartesian maps required a dummy unit-length measurement to render reasonably in Traffic Editor I. Now it sets a scale of `1.0` for Cartesian maps when scaling lane widths in the GUI.
"Nothing should have changed" in the behavior of existing reference-image based maps. Will build and test on the …
> Feature: serve BuildingMap message when loading GeoJSON file in building_map_server

- rmf_traffic_editor/gui/layer.cpp
- rmf_traffic_editor/gui/layer.h
- rmf_traffic_editor/gui/level.cpp
Previously, when editing maps with `cartesian_meters` coordinate system, layer images would render upside-down. This PR fixes that. No change to maps with `reference_image` coordinate system. Tested on all demo maps (which are all `reference_image` based) and they all render as expected.
> flip layer images right-side up in cartesian meters mode

- rmf_building_map_tools/building_map/building.py
Minimal PR that just copies a `map_version` field (if present in a `.building.yaml` file) into GeoJSON generated from it. 
> if map_version is present, copy it into GeoJSON

- rmf_building_map_tools/building_map_model_downloader/building_map_model_downloader.py
- rmf_building_map_tools/pit_crew/pit_crew.py
This PR addresses two issues related to fetching models from fuel:
* We will now always use the `ign=True` mode since we are always caching models in the `.ignition/fuel` model cache.
* We will ignore all spaces in model names when deciding if a local model copy matches a model on fuel. Sometimes the models on fuel are inconsistent about their use of spaces, and when that happens pit crew would accidentally re-download it (but this is fixed in this PR).
> Always use ign=True and remove spaces when comparing model names

- rmf_building_map_tools/building_map/building.py
- rmf_building_map_tools/building_map/level.py
- rmf_building_map_tools/building_map/model.py
- rmf_building_map_tools/building_map/passthrough_transform.py
- rmf_building_map_tools/building_map/wgs84_transform.py
- rmf_traffic_editor/gui/editor.cpp
- rmf_traffic_editor/gui/level.cpp
- rmf_traffic_editor/gui/main.cpp
- rmf_traffic_editor/gui/map_tile_cache.cpp
- rmf_traffic_editor/gui/map_view.cpp
- rmf_traffic_editor/gui/map_view.h
- rmf_traffic_editor/gui/model.cpp
- rmf_traffic_editor/gui/model.h
Hoping this patch will help handle the 
- latlon translation behavior for models ( previously, builds break when adding models due to WGS84 translation not having a "rotation" variable
- change naming convention for model positions to lat/lon instead of x/y for consistency
- apply offsets to the camera as well, so the camera view appears immediately over the working area
> Handle simulation offsets for models and cameras

- rmf_traffic_editor/gui/editor.cpp
In image-based maps (which almost everyone is currently using), there was some ambiguity about what the `x(m)` and `y(m)` properties panel meant when a vertex was selected. Due to long-ago historical reasons, it was simply dividing the pixel coordinate by the calculated scale of the floorplan image. This works fine for single-level worlds, but it caused problems in multi-level worlds, because the `x(m)` and `y(m)` coordinates were in meters relative to the corner of that level's floorplan image. Typically, multi-floor maps require some translation (guided by fiducials) to align the floorplan images, and this translation was not incorporated into the vertex properties panel.
This PR fixes this, so that the `x(m)` and `y(m)` coordinates are now in the metric frame of the reference level. …
> fix #419 by calculating transformed x/y in image-based maps

- .github/workflows/ci.yaml
- .github/workflows/ci_rolling.yaml
- .github/workflows/pycodestyle.yaml
- rmf_traffic_editor/CMakeLists.txt
Haven't tested this yet on Jammy, but I think this might fix the `rolling` builds which are currently failing on Ubuntu Jammy. At least, this doesn't break `galactic` on Ubuntu Focal.
> fix cmake ament_index_cpp dependency for rolling

- rmf_traffic_editor/gui/map_view.cpp
- rmf_traffic_editor/gui/new_building_dialog.ui
For WGS 84 (latitude / longitude) map files, this PR will use the URL of our new tile server, which is holding OpenStreetMap's full planet data. This will allow detailed OpenStreetMap background tiles to show up in the Traffic Editor GUI when used in WGS 84 (georeferenced) mode, anywhere in the world.
> change URL to global tile server.

- rmf_traffic_editor/gui/editor.cpp
- rmf_traffic_editor/gui/level.cpp
- rmf_traffic_editor/gui/map_view.cpp
- rmf_traffic_editor/gui/vertex.cpp
There was an issue with Qt font size scaling for Cartesian-meters maps: it seems at least on Linux, the Qt font size cannot be smaller than 1.0  which is normally fine, but when rendering the QGraphicsScene for Cartesian meter-scale maps, often we will want fonts that are significantly smaller than 1.0 in order to not have the font size appear huge in the scene. For reasons unknown, it seems that a reasonable workaround is to calculate 10x the font size we want, and then use 0.1 scaling in the Qt transform on the resulting QGraphicsSimpleTextItem
This PR also fixes a few remaining non-scaled pen widths in the polygon tool, which make the floor polygon border look silly in Cartesian-meters mode.
Tested against all of the `rmf_demos` maps, as well as some non-public Cartesian-meters maps. …
> better vertex text size in meter-scale maps

- rmf_building_map_tools/building_crowdsim/navmesh/file_writer.py
- rmf_building_map_tools/building_crowdsim/navmesh/polygon_factory.py
Since Python 3.10 (default in 22.04) `collections` is deprecated hence rmf_traffic_editor fails to build maps.
Move to `collections.abc`
> [Humble] Move to collections.abc for crowdsim

- rmf_traffic_editor/gui/lift.cpp
Stumbled upon this issue when using traffic editor under Ubuntu 22.04 / Humble, it seems to be due to iteration in yaml-cpp not working as intended. Specifically, the iteration goes past the end of the container and traffic editor segfaults, for example when parsing the clinic world with a lift and some levels, I added a printout to print the name of the level and the name of the door and the following happened:
```
Parsing level L1
Found door lift_1_door
Found door null
Found door null
Thread 1 "traffic-editor" received signal SIGSEGV, Segmentation fault.
YAML::Node::Type (this=0x7fffffffb050) at /usr/include/yaml-cpp/node/impl.h:85
85	  return m_pNode ? m_pNode->type() : NodeType::Null;
(gdb) where
#0  YAML::Node::Type (this=0x7fffffffb050) at /usr/include/yaml-cpp/node/impl.h:85
#1 …
```
> Use index based iterator to avoid yaml cpp bug

- rmf_building_map_tools/building_map/transform.py
Replace deprecated `np.asscalar()` calls with equivalent `.item()` calls, so that build will succeed on latest `numpy`
Should fix #437
> remove usage of deprecated np.asscalar()

- rmf_building_map_tools/building_map_server/building_map_server.py
In some cases where we create `.building.yaml` files without floorplans images and also without any scale parameters, `building_map_server` will crash when trying to access `level.transform.scale`. This PR aims to address this by only attempting to populate image properties if the file exists.
> building_map_server crashes when level scale is not defined

- rmf_building_map_tools/CHANGELOG.md
- rmf_building_map_tools/package.xml
- rmf_traffic_editor/CHANGELOG.md
- rmf_traffic_editor/package.xml
- rmf_traffic_editor_assets/CHANGELOG.md
- rmf_traffic_editor_assets/package.xml
- rmf_traffic_editor_test_maps/CHANGELOG.md
- rmf_traffic_editor_test_maps/package.xml
We need a new release of the package for 22.04 / Humble since the old version fails building maps because of an issue with deprecated usage of `collections` (specifically [this PR](https://github.com/open-rmf/rmf_traffic_editor/pull/432) needs to be released).
I bumped and updated the changelogs to 1.6.0 since this will be the first version targeting Humble.
We should probably also merge https://github.com/open-rmf/rmf_traffic_editor/pull/444 since maps packages might end up being built empty otherwise.
> Update changelogs and switch to markdown

- rmf_building_map_tools/CHANGELOG.md
- rmf_building_map_tools/package.xml
`pit_crew` uses ignition-fuel-tools to fetch the models from the Fuel server but it is not listed as a dependency, which causes model download to silently fail if tools are not installed on the user's machine.
Add it as a dependency to the `package.xml`
Note that this will introduce an Ignition dependency on the package, which should be kept in sync with other packages across the RMF stack. The chosen version is the one shipped with Fortress
> Add Fuel tools dependency to rmf_building_map_tools

- rmf_building_map_tools/pit_crew/pit_crew.py
- rmf_building_map_tools/pit_crew/usage_examples.py
- rmf_traffic_editor_assets/README.md
* Migrated to using `gazebosim` Fuel server url, possibly to help with model download stability
> Migrate to using gzsim server url for fuel

- rmf_building_map_tools/CHANGELOG.md
- rmf_building_map_tools/building_map/level.py
Correctly generate `dock_name` and `undock_name` when two waypoints with a `dock_name` property are connected to each other.
Previously, there was an if / else statement to determine whether the dock was at the beginning or end of the lane, as such:
```
dock_name = None
dock_at_end = True
if 'dock_name' in v2.params:  # lane segment will end at dock
dock_name = v2.params['dock_name'].value
elif 'dock_name' in v1.params:
dock_name = v1.params['dock_name'].value
dock_at_end = False
```
This logic wasn't able to deal with the case where both start and end waypoint have a `dock_name` property, in which case the generated navgraph would be incorrect.
The statements have now been split in two separate if statements to make sure all the possible combinations are properly accounted for. I also …
> Fix navgraph generation for connected docking waypoints

- rmf_building_map_tools/building_map/level.py
- rmf_traffic_editor/gui/edge.cpp
- rmf_traffic_editor/gui/vertex.cpp
This PR adds a new string parameter to lane parameters called `mutex`.
I briefly investigated making this an effectively optional property added through clicking the `Add Property` button but that turned out to be a lot more involved than expected since `Add Property` has historically only been used for vertex properties and it has vertex logic quite built-in, so the refactor would have been a lot larger.
I found a small duplicated snippet when parsing speed limit so took the chance to remove it. The parameter was being added twice in the same code block.
> Add mutex to lane parameters

- rmf_building_map_tools/building_map/building.py
This provides information about door geometry to the navigation graphs, allowing the fleet adapters to use geometry to identify when a robot will or will not be passing through a door.
> Include door information in nav graphs

- rmf_traffic_editor/gui/level.cpp
- rmf_traffic_editor/gui/vertex.cpp
- rmf_traffic_editor/gui/vertex.h
Vertices can now be given a merge radius which indicates how close to a vertex a robot is allowed to be to approach the vertex without using a lane.
> Add merge radius option for vertices

- rmf_traffic_editor/gui/building_dialog.cpp
Without this PR, if Generate CRS is empty when editing Building Properties, the saved building yaml will have `generate_crs` with empty value and this caused [this](https://github.com/open-rmf/rmf/discussions/407).
```
parameters:
generate_crs = [1, ""]
```
> Fix empty generate_crs in building yaml.

- rmf_building_map_tools/building_map/floor.py
I was trying a clean build of RMF Demos and ran into a type error when trying to compile maps. This PR fixes the type error. I'm not sure what triggered it in the first place TBH.
> Handle geometry collections

- rmf_building_map_tools/pit_crew/pit_crew.py
The default number of models that fuel returns is 20. This PR makes the number of models returned per page 5x larger, meaning fewer calls are made, and pagination completes much faster.
Setting the `per_page` to higher than 100 causes fuel to reject the arg and drop you back down to 10 models per page.
This mostly impacts people building from scratch, since the greatest impact is on initial building of the model cache.
> Speed up pagination for pit_crew

- rmf_building_map_tools/pit_crew/pit_crew.py
There is a duplicated model in fuel which break pit crew's cache. In order to not break existing caches, I just make an exception for that model.
**If your pull request is a bug fix, delete this line and all the below lines.**
**If your pull request is a feature implementation, delete this line and all the above lines.**
> Workaround fuel duplicated model

- rmf_building_map_tools/building_map/floor.py
Similar to https://github.com/open-rmf/rmf_traffic_editor/pull/476, `shapely` migration requires a minor [update](https://shapely.readthedocs.io/en/stable/migration.html#multi-part-geometries-will-no-longer-be-sequences-length-iterable-indexable) to our code. Without this PR fix the following error will occur when building certain maps that involve MultiPolygon: `TypeError: 'MultiPolygon' object is not iterable`
> Fix MultiPolygon not iterable

- rmf_traffic_editor/gui/building.cpp
The reference level name variable was not correctly reset, so when working with a file that has the reference level name set to a value, then loading one where it is not set to anything, the variable wouldn't be reset and it would be saved to the new building.
Reset the `reference_level_name` if it's empty when loading a building.
> Fix reference file name being kept when loading new building

- rmf_traffic_editor/gui/building.cpp
> Fix reference file name being kept when loading new building (#501)

- rmf_traffic_editor/gui/level.cpp
- rmf_traffic_editor/gui/level.h
- rmf_traffic_editor/gui/lift_table.cpp
Continuation of #509 
- Delete button in `lift_table` to remove lift from map and yam
- Delete any lift cabin way point and any edges connected to said way point
> Introducing lift delete button

- rmf_building_map_tools/building_map/floor.py
Cherry pick #496 to `humble`, _from what I understand_ the version that is shipped in [Ubuntu 22.04 is 1.8.0](https://packages.ubuntu.com/jammy/python3-shapely). Also from what I understand shapely 1.8.0 prints a deprecation warning https://shapely.readthedocs.io/en/stable/migration.html#multi-part-geometries-will-no-longer-be-sequences-length-iterable-indexable so this should be OK to backport (and avoid issues for people that might have a newer version of shapely but are using the `humble` repos).
Note that I don't have a 22.04 machine so I couldn't really test this
> Cherry-pick Shapely 1.8.0 deprecations (#496, #476)

- rmf_traffic_editor/gui/building.cpp
- rmf_traffic_editor/gui/building.h
- rmf_traffic_editor/gui/editor.cpp
- rmf_traffic_editor/gui/fiducial.cpp
- rmf_traffic_editor/gui/fiducial.h
- rmf_traffic_editor/gui/lift.cpp
- rmf_traffic_editor/gui/lift.h
This PR aims to solve the lift alignment issue presented in https://github.com/open-rmf/rmf_traffic_editor/issues/505.
There are two issues to resolve.
Firstly is the graphics of the lift cabin itself, and secondly is the vertex within the lift.
For the lift cabin, the methodology is straight forward.
We defined a function to calculate a mean rotation based on the fiducials available and store it as a new variable in the transform class. Then when a `compute_transform` function is called, the rotation will be used to calculate the correct translation between levels. Then the transform will flow down to the `draw` function of the lift, which will use the same rotation to calculate the position of the cabin in the level.
We still need to shift the `lift_cabin` vertex. Right now, all …
> Fix lift cabin graphics on rotated floor plans

- rmf_traffic_editor/gui/building.cpp
From PR https://github.com/open-rmf/rmf_traffic_editor/pull/513, the `compute_transform` function is modified to take into consideration level rotations when doing inter-level transformation.
But a segmentation fault will occur when a new level is created because there are no fiducials.
I've added a conditional check to make sure that the fiducials are 2 or more, before allowing the function to continue.
> Add a conditional check for level transformation

- rmf_building_map_tools/building_map/building.py
- rmf_building_map_tools/building_map/generator.py
- rmf_building_map_tools/building_map_generator/_init_argparse.py
- rmf_building_map_tools/building_map_generator/building_map_generator.py
* Flag to skip calculating and setting initial world camera pose
This flag allows users to set their preferred initial world camera pose in their template file, and skip our usual naive calculation and setting. Users can then ensure that their gazebo world will initialize and view the exact scene in simulation that they prefer.
> Add flag to skip calculating and setting camera pose

- rmf_building_map_tools/building_map/building.py
- rmf_building_map_tools/building_map/generator.py
- rmf_building_map_tools/building_map_generator/_init_argparse.py
- rmf_building_map_tools/building_map_generator/building_map_generator.py
This PR cherry picks two minor features to jazzy:
* Customizing the world base file from a template #519 
* Add a flag to skip calculation of camera pose #523 
They are new optional flags that shouldn't introduce any breakage in the released packages
> Cherry pick optional build rmf_building_map_tools parameters to Jazzy

- rmf_building_map_tools/building_map_model_downloader/building_map_model_downloader.py
- rmf_building_map_tools/pit_crew/pit_crew.py
Ref https://github.com/open-rmf/rmf/discussions/578#discussioncomment-11713951, fuel pipeline wasn't used for some time, but while fixing it I bumped into several other issues that I bundled in this PR.
A series of issues in pit_crew:
* The root cause of the issue, if a model with a different organization name is uploaded `pit_crew` will report it as downloadable, the pipeline will later try to download it but fail. Fixed the `downloadable` generation logic https://github.com/open-rmf/rmf_traffic_editor/pull/522/commits/d392b76d363d78933c8ea25daefdb4a3bf52b9a8.
* The above didn't quite bubble up because in the bare http pipeline (which is what we use) we check a _tuple_ for true / false, so returning `(False, None)` actually evaluates to True, fixed in …
> Fix pit crew missing models and authorship logic

- rmf_building_map_tools/building_map_server/building_map_server.py
The bug in this proposed fix is for allowing numerically-labelled map names.
Eg. If map name in `.building.yaml` is `L1`, no error when starting up RMF Traffic. Map can be displayed in `RViz` window.
Eg. If map anme in `.building.yaml` is `1`, RMF Traffic crashes. Map won't be displayed in `RViz` window.
Explicit-cast level name to string when generating `Level` msg.
Explicit-cast level name associated to lift when generating `Lift` msg.
> Fix to Allow Numerically-Labelled Map

- .github/workflows/pycodestyle.yaml
- rmf_building_map_tools/building_crowdsim/config/behavior_file.py
- rmf_building_map_tools/building_crowdsim/config/configfile_generator.py
- rmf_building_map_tools/building_crowdsim/config/plugin_file.py
- rmf_building_map_tools/building_crowdsim/navmesh/connection.py
- rmf_building_map_tools/building_crowdsim/navmesh/edge.py
- rmf_building_map_tools/building_crowdsim/navmesh/file_writer.py
- rmf_building_map_tools/building_crowdsim/navmesh/lane.py
- rmf_building_map_tools/building_crowdsim/navmesh/navmesh_generator.py
- rmf_building_map_tools/building_crowdsim/navmesh/object_manager.py
- rmf_building_map_tools/building_crowdsim/navmesh/polygon.py
- rmf_building_map_tools/building_crowdsim/navmesh/polygon_factory.py
- rmf_building_map_tools/building_crowdsim/navmesh/vector.py
- rmf_building_map_tools/building_map/doors/door.py
- rmf_building_map_tools/building_map/level.py
- rmf_building_map_tools/building_map/templates/gz_world.sdf
- rmf_building_map_tools/building_map_server/building_map_server.py
- rmf_building_map_tools/building_map_server/test/test_map_client.py
- rmf_building_map_tools/test/building_crowdsim/test_build_navmesh.py
In gz-sim 9, the physics plugin is automatically added. By adding it explicitly in our worlds, we end up creating two competing physics plugins that can end up clashing with each other.
This PR removes the physics plugin from the template so that we don't have that clash.
> Remove redundant physics plugin
