gui/edge.cpp
gui/edge.h
gui/editor.cpp
gui/editor.h

This is useful for taking quick measurements of things on the architectural drawings.

show edge and vertex stats in meters in the property editor

---

generators/generator/generator.py
generators/generator/level.py

When generating nav graphs, calculate if lane segments intersect with doors. If so, add the door name to the parameters of the lane segment.

calculate lane segment intersections with doors

---

.github/workflows/build.yaml
README.md
traffic_editor/README.md

fix build GitHub action script, by `apt update` before `apt install` in the workflow script. Happy badge again.

update before installing in github workflow

---

building_map_tools/building_map/level.py
building_map_tools/building_map/model.py
traffic_editor/gui/vertex.cpp

* add vertex parameters for spawning robot type and name
* use those parameters when generating a gazebo world

robot parameters for spawning and Gazebo world generation

---

building_map_tools/building_map/doors/double_sliding_door.py
building_map_tools/building_map/level.py
traffic_editor/gui/vertex.cpp

also some more progress towards doors before I got distracted by docking :smile:

add dock points and generate docking nav graph params

---

building_map_tools/building_map/__init__.py
building_map_tools/building_map/building.py
building_map_tools/building_map/doors/door.py
building_map_tools/building_map/doors/double_sliding_door.py
building_map_tools/building_map/doors/double_swing_door.py
building_map_tools/building_map/floor.py
building_map_tools/building_map/generator.py
building_map_tools/building_map/level.py
building_map_tools/building_map/model.py
building_map_tools/building_map_generators/building_map_gazebo.py
building_map_tools/building_map_generators/building_map_nav.py
building_map_tools/setup.py
traffic_editor/gui/edge.cpp

* a bunch of flake8 fixes
* generate Gazebo XML markup for doors

Generate doors

---

building_map_tools/building_map/level.py

Fix orientation on unidirectional edge conversion

---

building_map_tools/building_map/level.py
traffic_editor/CMakeLists.txt
traffic_editor/gui/edge.cpp
traffic_editor/gui/editor.cpp
traffic_editor/gui/editor.h
traffic_editor/gui/layer.cpp
traffic_editor/gui/layer.h
traffic_editor/gui/layer_dialog.cpp
traffic_editor/gui/layer_dialog.h
traffic_editor/gui/level.cpp
traffic_editor/gui/level.h
traffic_editor/gui/map.cpp
traffic_editor/gui/map.h
traffic_editor/gui/model.cpp
traffic_editor/gui/polygon.cpp
traffic_editor/gui/vertex.cpp

* modeless dialog to rotate/scale/translate robot maps to align them to a floorplan drawing
* save YAML with alphabetical keys so that diffs are sane

Rendering layers controls

---

traffic_editor/CMakeLists.txt
traffic_editor/gui/editor.cpp
traffic_editor/gui/editor.h
traffic_editor/gui/editor_model.cpp
traffic_editor/gui/level.cpp
traffic_editor/gui/level.h
traffic_editor/gui/map.cpp
traffic_editor/gui/map.h
traffic_editor/gui/model_dialog.cpp
traffic_editor/gui/model_dialog.h

* model insertion and preview is now in its own dialog, rather than clutter the main editing UI
* allow deletion of existing (unused) vertices
* allow deletion of models
* various minor stylistic cleanups

Editor UI cleanup

---

traffic_editor/gui/editor.cpp
traffic_editor/gui/editor.h
traffic_editor/gui/main.cpp

* keep track if a document has been modified
* prompt to save changes on exit

Set modified flag

---

traffic_editor/gui/editor.cpp

deal more gracefully with an empty world by not crashing

---

traffic_editor/gui/editor.cpp
traffic_editor/gui/preferences_keys.cpp
traffic_editor/gui/preferences_keys.h

use qsettings to save/restore window position and size

---

building_map_tools/building_map/building.py

fix #54, update yaml key names

---

traffic_editor/gui/editor.cpp

Finish implementing #63 to make drawing long sequences of wall edges and traffic lanes less painful. Vertices are now created as needed every click. If a click is within an existing vertex, it "snaps" the click to that vertex and avoids creating a new one. The next edge (wall or lane) automatically starts creation immediately after each click, so you can just click-click-click-click to create 3 edges, for example. It's fun now. :tada:

finish implementing #63 to allow continuous clicks for edge creation

---

traffic_editor/gui/building.cpp
traffic_editor/gui/building_level.cpp
traffic_editor/gui/building_level.h
traffic_editor/gui/building_level_table.cpp

Fix initial creation workflow

---

building_map_tools/building_map/building.py
building_map_tools/building_map/fiducial.py
building_map_tools/building_map/floor.py
building_map_tools/building_map/level.py
building_map_tools/building_map/model.py

* change building scale calculations so they happen after parsing is completed
* calculate scale and offsets relative to the "reference level" in the building map generator so that fiducials are aligned in generated Gazebo worlds

Calculate scale and translation to align building levels

---

.github/workflows/style.yaml
README.md
building_map_tools/building_map/building.py
building_map_tools/building_map/doors/door.py
building_map_tools/building_map/doors/double_sliding_door.py
building_map_tools/building_map/doors/double_swing_door.py
building_map_tools/building_map/floor.py
building_map_tools/building_map/level.py
building_map_tools/building_map_generators/building_map_gazebo.py
building_map_tools/building_map_server/building_map_server.py
building_map_tools/building_map_server/test/test_map_client.py
building_map_tools/setup.py

* add `style` action that calls `pycodestyle`
* many small tweaks to fix Python code style throughout the world generator

Pycodestyle action and many python style fixes

---

building_map_tools/building_map/building.py
building_map_tools/building_map/doors/door.py
building_map_tools/building_map/doors/double_sliding_door.py
building_map_tools/building_map/doors/double_swing_door.py
building_map_tools/building_map/floor.py
building_map_tools/building_map/generator.py
building_map_tools/building_map/level.py
building_map_tools/building_map/templates/gz_world.sdf
building_map_tools/building_map/templates/ign_world.sdf
building_map_tools/building_map_generators/building_map_ignition.py
building_map_tools/setup.py

* add a separate generator python entry point
* a few minor tweaks to branch between ignition and gazebo generation products (doors, etc.)
* create gazebo world template file

Ignition generator

---

building_map_tools/building_map/level.py

* forgot to add vertical normal for wall "cap" triangles
* a few off-by-one errors in normal and texture vertex indexing :man_facepalming:

hopefully fix norm and texture indexing in wall obj files

---

building_map_msgs/package.xml

Just adding missing geometry_msgs to package.xml on building_map_msgs package

adding missing pkg dependencies

---

building_map_tools/building_map_generators/pit_crew/__init__.py
building_map_tools/pit_crew/__init__.py
building_map_tools/pit_crew/pit_crew.py
building_map_tools/pit_crew/usage_examples.py
building_map_tools/setup.py

```
(   (                 (
)⧹ ))⧹ ) .   )    (   )⧹ )    (  (
(()/(()/` )  /(    )⧹ (()/((   )⧹))(   .
/(_)/(_)( )(_)) (((_) /(_))⧹ ((_)()⧹ )
(_))(_))(_(_())  )⧹___(_))((_)_(())⧹_)()
| _ |_ _|_   _|  (/ __| _ | __⧹ ⧹((_)/ /
|  _/| |  | |    | (__|   | _| ⧹ ⧹/⧹/ /
|_| |___| |_|     ⧹___|_|_|___| ⧹_/⧹_/
~ take a REST, and top-up your Fuel ~
```
`pit_crew` is an Ignition Fuel REST client and library that helps fetch and manage your model directory for Gazebo. ⛽
This library is fully documented with Sphinx compatible docstrings! And also includes logging capabilities!
- Creating a cache of available model names on ignition fuel
- Looking up the gazebo models path when encountering the model list to load first
- Checking if those models exist in the cache (and if they don't, updating the …

Unleash the pit_crew!

---

README.md
building_map_tools/building_map_generator/building_map_generator.py

Adding instructions to install pit_crew dependency

---

building_map_tools/pit_crew/pit_crew.py

Just a simple hotfix (:
-CH3EERS!

Make pit_crew robust against missing author names

---

building_gazebo_plugins/src/slotcar.cpp

* The elevation of the robot in simulation is used to populate `location.level_name`. This makes reporting of the robots location more accurate for multi-level simulations
* `RobotState` is now published at 2Hz which greatly reduces load on fleet adapters

Slotcar update

---

building_map_tools/building_map_generator/building_map_generator.py

Removes all pit_crew calls when the no download argument is passed to building_map_generator.

Allow for non-internet builds

---

building_map_tools/package.xml

Signed-off-by: Chen Bainian <brian97cbn@gmail.com>
same as #167

Correct dependee to python3-requests

---

building_map_tools/building_map_model_downloader/building_map_model_downloader.py
building_map_tools/setup.py

Implements a script to assist in model downloading without needing to also build the worldfile from a specified traffic_editor file.

Implement model downloader

---

building_map_tools/building_map_generator/_init_argparse.py
building_map_tools/building_map_generator/building_map_generator.py

Any required model downloading will occur using `building_map_model_downloader` instead.

Remove duplicated code in map generator

---

test_maps/CMakeLists.txt

* calling `message` in `add_custom_command` creates interesting issues

Move message call outside of custom command call

---

building_map_tools/building_map/building.py
building_map_tools/building_map/level.py

* Fix for https://github.com/osrf/traffic_editor/issues/210
* Tested and working

Model counts to be owned by Building, and passed to each Level

---

.github/workflows/build.yaml
.github/workflows/style.yaml

To enable checks on PRs coming from forks.

Add style / build checks on pull requests

---

building_map_tools/building_map_server/building_map_server.py

Non-critical change. This helps in debugging in here: https://github.com/osrf/rmf_schedule_visualizer/pull/78

populate floorplan name to msg

---

building_sim_plugins/building_plugins_common/CMakeLists.txt

Fixes symbol lookups at runtime as reported [here](https://github.com/osrf/rmf_demos/pull/152#issuecomment-720369963)

Added ament exports for crowd simulation common

---

building_sim_plugins/building_plugins_common/CHANGELOG.rst
building_sim_plugins/building_plugins_common/include/building_sim_common/slotcar_common.hpp
building_sim_plugins/building_plugins_common/src/slotcar_common.cpp

This PR introduces a new pause feature which is needed by https://github.com/osrf/rmf_core/pull/226.
It also fixes a few bugs that have been lingering in the slotcar plugin for some time now.

Add pausing feature

---

building_sim_plugins/building_plugins_common/include/building_sim_common/slotcar_common.hpp
building_sim_plugins/building_plugins_common/src/slotcar_common.cpp

tested with office world, not breaking.
- pub idle mode
- fix by increase charging radius

idle mode when slotcar is stationary

---

building_map_tools/building_map/templates/ign_world.sdf

Update the world generation template to increase the physics' step size by 10 (effectively increasing the simulation speed by the same factor), as well as adding all the new plugins developed in Dome and the `toggle_charging` plugin for slotcar.

Ign rtf optimizations and GUI plugins

---

traffic_editor/gui/editor.cpp
traffic_editor/gui/editor.h

to repro: press T and then M, you should get a crash due to deleting un-initialized pointers. also this PR cleans up some unused variables

remove unused variables, fix delete crash, initialize to nullptr

---

rmf_traffic_editor/gui/editor.cpp

Clarify labels on add/delete GUI buttons, implement #323 

clarify labels on property add/delete buttons

---

README.md
rmf_building_map_tools/package.xml

Partial fix https://github.com/open-rmf/rmf/issues/27, test download `shapely`, `py-yaml`, `py-requests` with `rosdep`. Minor update on Readme.md

clean dep and update readme

---

rmf_building_map_tools/CHANGELOG.rst
rmf_building_map_tools/package.xml
rmf_traffic_editor/CHANGELOG.rst
rmf_traffic_editor/package.xml
rmf_traffic_editor_assets/CHANGELOG.rst
rmf_traffic_editor_assets/package.xml
rmf_traffic_editor_test_maps/CHANGELOG.rst
rmf_traffic_editor_test_maps/package.xml

Signed-off-by: Marco A. Gutierrez <marco@openrobotics.org>

Version bump and changelogs for 1.3.0

---

rmf_building_map_tools/package.xml

Adding missing `python3-pytest` dependency.

Added missing python3-pytest dependency

---

rmf_building_map_tools/package.xml
rmf_traffic_editor/package.xml
rmf_traffic_editor_assets/package.xml
rmf_traffic_editor_test_maps/package.xml

Signed-off-by: Marco A. Gutierrez <marco@openrobotics.org>

adding maintainer for buildfarm notifications

---

rmf_building_map_tools/CHANGELOG.rst
rmf_building_map_tools/package.xml
rmf_traffic_editor/CHANGELOG.rst
rmf_traffic_editor/package.xml
rmf_traffic_editor_assets/CHANGELOG.rst
rmf_traffic_editor_assets/package.xml
rmf_traffic_editor_test_maps/CHANGELOG.rst
rmf_traffic_editor_test_maps/package.xml

Signed-off-by: Marco A. Gutierrez <marco@openrobotics.org>

Updating changelogs and version for galactic

---

rmf_building_map_tools/building_map_model_downloader/building_map_model_downloader.py
rmf_building_map_tools/pit_crew/pit_crew.py

Fixes missing models bug uncovered with fix https://github.com/open-rmf/rmf_traffic_editor/pull/412
* Makes model paths available through `pit_crew`
* exports downloaded models to `export_path`

Pit crew makes model paths available, when checking for missing models, for exporting

---

.github/workflows/ci_rolling.yaml
.github/workflows/pycodestyle.yaml
rmf_traffic_editor/CMakeLists.txt

Merge Rolling/Jammy fixes from main into this pre-release branch

fix cmake ament_index_cpp dependency for rolling (#423)

---

rmf_building_map_tools/model_downloader/model_downloader.py

Fixes https://github.com/open-rmf/rmf/issues/172. 
Fixed call to `download_models`, since change in API.

Fixed usage of download_models

---

rmf_building_map_tools/building_map_model_downloader/building_map_model_downloader.py
rmf_building_map_tools/pit_crew/pit_crew.py

Fixes https://github.com/open-rmf/rmf_traffic_editor/issues/451
**If your pull request is a bug fix, delete this line and all the below lines.**
**If your pull request is a feature implementation, delete this line and all the above lines.**
Exit model downloader script with non-zero exit code, to fail any calls in package building.

Exiting model downloader with non-zero exit code

---

rmf_building_map_tools/building_map_model_downloader/building_map_model_downloader.py

Related to https://github.com/open-rmf/rmf_traffic_editor/issues/451. Added 5 retries for each model download, I hope that is enough.

Added 5 retries for model downloading failure

---

rmf_traffic_editor_test_maps/CMakeLists.txt

Fixes https://github.com/open-rmf/rmf/actions/runs/3612422372/jobs/6087520413#step:4:16205
Updated model downloading step to use the correct flags, pretty much the same as in `rmf_demos_maps`

Fix test map generation with new commands

---

rmf_building_map_tools/CHANGELOG.rst
rmf_building_map_tools/package.xml
rmf_building_map_tools/setup.py
rmf_traffic_editor/CHANGELOG.rst
rmf_traffic_editor/package.xml
rmf_traffic_editor_assets/CHANGELOG.rst
rmf_traffic_editor_assets/package.xml
rmf_traffic_editor_assets/setup.py
rmf_traffic_editor_test_maps/CHANGELOG.rst
rmf_traffic_editor_test_maps/package.xml

Merge commit instead of squash merge.

Bump 1.7.0

---

rmf_building_map_tools/building_map_model_downloader/building_map_model_downloader.py
rmf_traffic_editor_test_maps/CMakeLists.txt

Backport #470 to humble

---

rmf_building_map_tools/building_map_model_downloader/building_map_model_downloader.py
rmf_traffic_editor_test_maps/CMakeLists.txt

Backport #470 to iron

---

rmf_building_map_tools/building_map/building.py

An upcoming version of `rmf_traffic` will be able to take advantage of lift properties, so we need to export that information into the nav graphs.

Export lifts to nav graphs

---

rmf_building_map_tools/pit_crew/pit_crew.py

**If your pull request is a bug fix, delete this line and all the below lines.**
**If your pull request is a feature implementation, delete this line and all the above lines.**

backport pit crew fixes
